### ISSUE TITLE
Review and merge volunteer contributed improvements

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-android#104]
Two PRs have been submitted from a volunteer. Review these, try them out, get them to comply with our coding standards, and get them merged.

- [x] https://github.com/medic/medic-android/pull/100
- [x] https://github.com/medic/medic-android/pull/101

**Comment by mrsarm** [comment]
Closing with 1 updated and merged, and the other closed because was very outdated and not aligned with issues in the backlog and current usage of the app.
