### ISSUE TITLE
Use newest Simprints version

### ISSUE THREAD

**Issue by abbyad** [medic/cht-android#132]
With the Simprints integration we are using version `1.0.11` which is from [before 2017](https://sites.google.com/simprints.com/simprints-for-developers/releases/pre-2018-releases/1-1). We should update to the [latest version](https://sites.google.com/simprints.com/simprints-for-developers/releases) which brings in substantial improvements, like face recognitionand new language support. 

**Note:** Using the newer version brings up the minimum supported Android version of the Simprints app to Android 6 (API level 23). This is outside of our control and a necessary requirement for any new project deploying with Simprints.

**Comment by garethbowen** [comment]
Closing - we're going to drop the integration until it's needed. #230
