### ISSUE TITLE
Investigate F-Droid for Medic Android app distribution

### ISSUE THREAD

**Issue by craig-landry** [medic/cht-android#147]
We currently use the Google Play Store to distribute our Android app. That platform has restrictions in place that are very reasonable for such a marketplace, but tend to be detrimental for our use cases and come with requirements to adhere with inapplicable policies.

One candidate for an alternative to the Google Play Store is F-Droid. This issue is to perform some investigation to determine the tradeoffs involved if we were to switch from the Google Play Store to F-Droid (either the F-Droid hosted service or if we were to run/host an instance of it ourselves).

Items to evaluate:
- [ ] How to build the medic-android app for F-Droid.
- [ ] Steps required for IT support or end users to set up F-Droid and install and update our app on their phones.
- [ ] What would it be like to handle publishing to the [official repository](https://f-droid.org/) - are we open enough?
- [ ] What is involved with running our own F-Droid repository and publishing there.

**Comment by newtewt** [comment]
This is the flow to setup a locally hosted F-Droid. Once everything is completed and the repo is added. The user can search for the Medic Mobile app and install.  The cool thing is after it is configured they can update an existing app installed via playstore with fdroid. It has a similar feel to if you sideload a new version in that it will prompt about installing and whether data is wiped. 


## Server Setup

Install their  [webtools](https://f-droid.org/docs/Installing_the_Server_and_Repo_Tools/?title=Installing_the_Server/Repo_Tools)
They have a docker executable of this as well to do the setup. Otherwise use `sudo apt-get install fdroidserver` on ubuntu

```
sudo mkdir /usr/share/nginx/www/fdroid
sudo chown -R $USER /usr/share/nginx/www/fdroid
cd /usr/share/nginx/www/fdroid
fdroid init
```
Copy apks to ` /usr/share/nginx/www/fdroid/repo/`

Run 
fdroid update --create-metadata

## Client Intall and Config

Install the android client from https://www.f-droid.org/
Navigate to Settings > Repositories
Press the plus sign
Add the repo server info. Locally it will be http://ip-address/fdroid/repo.
The guide says you can just navigate to http://ip-address/fdroid/repo in a browser and android should register the deeplink and take you to the add repo screen. However, I could not get this to work. 

> While you can serve the repository at an arbitrary URL, it is customary to make it available at an URL ending with /fdroid/repo/. A good reason to actually do this is that the F-Droid client sets up an intent filter and registers itself for such URLs. As a result, a user that has the F-Droid app installed and opens such a well-formed URL will have their device open F-Droid and guide them directly to adding the repository to it.


## Real World Setup

They detail the steps you should take to manage this in a [real world situation]( https://www.f-droid.org/en/docs/Setup_an_F-Droid_App_Repo/#real-world-setup
) here. Mainly the signing key for the repo and hosting are not on the same machine.

**Comment by craig-landry** [comment]
@newtewt to be sure I'm understanding correctly, if I have the app on my phone already, with important data stored locally, I can add F-Droid, then install the Medic app from F-Droid, and I can choose to retain my data?

**Comment by newtewt** [comment]
@craig-landry  I had the app installed from play store. Logged in to gamma.dev. Installed F-Droid and then the version hosted from my F-Droid repo. It prompted to install and with no data loss. The prompt felt like a side load prompt to me. After doing that install I was still logged in to gamma.dev.

**Comment by newtewt** [comment]
# Metadata
   There is a lot of metadata that can be added to make the F-Droid experience better for the user. 
   
   https://www.f-droid.org/en/docs/Build_Metadata_Reference/

#Update Process

Copy apks to the location where you did the isntall steps. `/usr/share/nginx/www/fdroid/repo/`
Run `fdroid update` this will update all the meta data and will delete the previous apks.

Client can pull down to refresh in the app and it should show immediately.  There is an update section that will list medic mobile if it is available.   

# Installing via bluetooth/nearby

This is an option in the app. I was only able to get it to work once between the three phones I have using the bluetooth option. There is supposedly support for NFC or android beam but following the instructions that didn't work.

**Comment by garethbowen** [comment]
Awesome work, thanks @newtewt !

Did you find any options for configuring the repo, for example, so we can invite users to install a specific app?

The Play Store has various release channels so you can have a beta release for testing before making it available to all users. Does FDroid have something equivalent?

We currently publish 3 apks - one for Android >10, and two different architectures for Android <10. The Play Store silently picks the right apk for your phone. Does FDroid also do this?

Can you outline the steps involved from an end user perspective, firstly for installing FDroid, and secondly for installing and upgrading our app from FDroid?

**Comment by newtewt** [comment]
@garethbowen as a general comment  the self hosting method of F-droid documentation seems to be a bit lacking. F-droid is very basic in its functionality compared to the app store. 

> Did you find any options for configuring the repo, for example, so we can invite users to install a specific app?

Self hosting I can't find very much of a user control. As in if a user has the repo added to their install they can install the app. 

> The Play Store has various release channels so you can have a beta release for testing before making it available to all users. Does FDroid have something equivalent?

I don't see anything about the channels specifically. I believe we would control this based on the repo. As in we would have a Prod repo, beta repo, and potentially an alpha repo. Although at that point I think it would make sense to just install from github actions artifact for say AT and then RT against the beta repo and eventually promote to the prod repo. 


> We currently publish 3 apks - one for Android >10, and two different architectures for Android <10. The Play Store silently picks the right apk for your phone. Does FDroid also do this?

I'll add this to my todo list. 

> Can you outline the steps involved from an end user perspective, firstly for installing FDroid, and secondly for installing and upgrading our app from FDroid?

The F-droid install and repo adding portion is outlined above. I'll add to my TODO to document the process once the repo has been added.

**Comment by newtewt** [comment]
> The Play Store has various release channels so you can have a beta release for testing before making it available to all users. Does FDroid have something equivalent?

I think these two notes are also related to this question. F-droid is not in the business of any sort of tracking. We do at least one anti-feature (tracking telemetry) but in a self hosted solution I'm not sure that matters. 

https://f-droid.org/en/docs/Anti-Features/

https://f-droid.org/en/docs/FAQ_-_App_Developers/#can-i-see-whos-installing-my-app

https://f-droid.org/en/docs/FAQ_-_App_Developers/#can-i-track-users-from-my-app

**Comment by mrjones-plip** [comment]
Based on some chats in `#devnull` about autoupdating APKs outside the Play Store, I'm adding some research notes here in case they're useful:
* Signal supports autoupdate of their [side load app](https://signal.org/android/apk/).  Not very well publicized, but [here's the commit](https://github.com/signalapp/Signal-Android/commit/9b8719e2d56a098502475bb5b2295c7a376d4caa) where they added the code.
* Here's a stack post of interest: [How to autoupdate android app without playstore?](https://stackoverflow.com/a/34251748)
* [rando blog post on the topic](https://www.legendblogs.com/update-app-from-internal-storage)


CC @craig-landry @newtewt & @garethbowen

**Comment by craig-landry** [comment]
cc @njogz

**Comment by garethbowen** [comment]
@craig-landry We should close this off, right?

**Comment by craig-landry** [comment]
Yup, thanks @garethbowen
