### ISSUE TITLE
Add an exception in GH actions to skip the build process when only README changes

### ISSUE THREAD

**Issue by mrsarm** [medic/cht-android#157]
We cannot skip CI but we should be able to skip at least the steps, specially the one that builds the app.

**Comment by craig-landry** [comment]
An alternative would be to do something like this:
```
if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
```

There is also a GitHub action (yeah, ironic) to handle this, which in their docs seem to handle some edge cases too:
https://github.com/marketplace/actions/ci-skip-action

**Comment by mrsarm** [comment]
I have implemented this in another PR trying to fix something else, but already in master: https://github.com/medic/cht-android/blob/d76e553cfe437b6b7899f847f046de1dd1999584/.github/workflows/build.yml#L3-L11
