### ISSUE TITLE
Replace deprecated ImagePicker

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-android#159]
The ImagePicker library we use is [deprecated](https://github.com/Mariovc/ImagePicker#imagepicker-deprecated-use-google-api-camerax), and the most recent version [crashes the app](https://github.com/medic/medic-android/issues/127), so we should migrate to another solution.

**Comment by garethbowen** [comment]
Scheduling for 4.0.0 because some of the solutions will not work on Android 4.4.

**Comment by latin-panda** [comment]
Adding a bit more of context:

Currently the users can't upload image, audio, video and file when using the cht-android app. This work will fix these type of questions and increase the compatibility with the [ODK standard](https://xlsform.org/en/ref-table/).

**Comment by latin-panda** [comment]
To add more info: 
Webapp's Enketo has a max limit of 32KB for each uploaded file. There's another ticket to increase this limit [here](https://github.com/medic/cht-core/issues/7529).

**Comment by latin-panda** [comment]
Ready for AT in [this PR](https://github.com/medic/cht-android/pull/245)

Please see the current limitations in[ the previous comment,](https://github.com/medic/cht-android/issues/159#issuecomment-1046735496) and send me any question you might have 🙂

This is one form we've been using to test, please include more cases as needed for testing.
<details>
<summary>xml form</summary>


```

<h:html xmlns="http://www.w3.org/2002/xforms" xmlns:h="http://www.w3.org/1999/xhtml">
	<h:head>
		<h:title>Photos on Android - Demo Form</h:title>

		<model>
			<instance>
				<photos-on-android id="photos-on-android">
					<my_photo/>
					<my_video/>
					<my_sound/>
					<my-any-file/>
					<meta>
						<instanceID/>
					</meta>
				</photos-on-android>
			</instance>

			<bind nodeset="/photos-on-android/my_photo" type="binary"/>
			<bind nodeset="/photos-on-android/my_video" type="binary"/>
			<bind nodeset="/photos-on-android/my_sound" type="binary"/>
			<bind nodeset="/photos-on-android/my-any-file" type="binary"/>
		</model>
	</h:head>

	<h:body>
		<upload ref="/photos-on-android/my_photo" mediatype="image/*">
			<hint>Select a picture or take a photo</hint>
			<label>Image widget</label>
		</upload>
		<upload ref="/photos-on-android/my_video" mediatype="video/*">
			<hint>Select a video</hint>
			<label>Video widget</label>
		</upload>
		<upload ref="/photos-on-android/my_sound" mediatype="audio/*">
			<hint>Select a sound?</hint>
			<label>Sound widget</label>
		</upload>
		<upload ref="/photos-on-android/my-any-file" mediatype="">
			<hint>Select a whatever?</hint>
			<label>File widget</label>
		</upload>
	</h:body>
</h:html>
```
</details>

**Comment by tatilepizs** [comment]
**User:** CHW
**Config:** Default
**Environment:** gamma
**cht-core version:** master
**Platform:** Mobile App. APK generated with branch `159-file-picker`

Tested in different Android version, all the images were uploaded successfully.

<details>
<summary>Samsung Galaxy S7 Edge, Android 7.0 (emulator - Kobiton)</summary>

<img width="300" alt="image" src="https://user-images.githubusercontent.com/94494491/158421259-4020d7d7-3d67-437f-89c6-607ffd457f2a.jpg">
<img width="300" alt="image" src="https://user-images.githubusercontent.com/94494491/158421384-a8446ba4-0fc4-4c20-8448-25efa771d9f3.jpg">
<img width="300" alt="image" src="https://user-images.githubusercontent.com/94494491/158421407-545d2d16-597e-425b-8987-ed56f8fddb7d.jpg">
<img width="300" alt="image" src="https://user-images.githubusercontent.com/94494491/158421429-257f29b2-a4ce-45ae-979c-8501a899291a.jpg">

</details>

<details>
<summary> Huawei P20 lite, Android 9 (real phone)</summary>

<img width="300" alt="image" src="https://user-images.githubusercontent.com/94494491/158428440-5a575728-662a-4223-8885-c3e8f3e6c31d.png">
<img width="300" alt="image" src="https://user-images.githubusercontent.com/94494491/158428508-fb541e22-d100-4113-a26c-142f4fc45ebc.png">
<img width="300" alt="image" src="https://user-images.githubusercontent.com/94494491/158428575-01c09c63-8692-46e6-a2af-11398c4cd41c.png">
<img width="300" alt="image" src="https://user-images.githubusercontent.com/94494491/158428629-a045f019-5a41-4761-b216-ef67f71cdfd0.png">
<img width="300" alt="image" src="https://user-images.githubusercontent.com/94494491/158428703-19390803-5efd-4445-b7f0-fce66e17b084.png">
<img width="300" alt="image" src="https://user-images.githubusercontent.com/94494491/158428765-12361eba-8ba7-4e0f-834c-e735f85ac55e.png">

</details>

<details>
<summary> Samsung Galaxy A50, Android 10 (emulator - Kobiton)</summary>

<img width="300" alt="image" src="https://user-images.githubusercontent.com/94494491/158422061-654fe54e-f09c-4ece-aa93-94c4babdf8ff.jpg">
<img width="300" alt="image" src="https://user-images.githubusercontent.com/94494491/158422177-40662c37-e977-4fea-b406-16ea3c7ed290.jpg">
<img width="300" alt="image" src="https://user-images.githubusercontent.com/94494491/158422215-4f9ce7ba-58df-4d6e-b3f1-871b3fb60e40.jpg">
<img width="300" alt="image" src="https://user-images.githubusercontent.com/94494491/158422194-5d3353a3-23da-4c67-84a5-b45e01c4aca5.jpg">

</details>

<details>
<summary> Samsung Galaxy S21, Android 11.0 (emulator - BrowserStack)</summary>

<img width="300" alt="image" src="https://user-images.githubusercontent.com/94494491/158422428-13050a44-0c43-4251-909f-445c48b9bc0a.png">
<img width="300" alt="image" src="https://user-images.githubusercontent.com/94494491/158422444-1bbfb009-2218-4de3-b37b-b27b2dd898ad.png">
<img width="300" alt="image" src="https://user-images.githubusercontent.com/94494491/158422454-fb90abb1-6bb5-4097-8476-163f6b1d1afa.png">
<img width="300" alt="image" src="https://user-images.githubusercontent.com/94494491/158422494-a4de5ac3-d52f-43f3-b742-97948428e89c.png">
<img width="300" alt="image" src="https://user-images.githubusercontent.com/94494491/158422579-4a2e747d-af62-44df-8a87-7bc2a9645582.png">

</details>

**Comment by latin-panda** [comment]
Thanks @tatilepizs for the detailed comment and great work testing in different Android versions! 

This work is merged into the main branch.
