### ISSUE TITLE
Spaces in URL on unbranded app cause errors

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-android#178]
## Overview

When entering in a URL on the unbranded app and accidentally entering space before or after the URL, errors are caused.

We should likely trim leading and trailing spaces for a better user experience since spaces at those positions in the URL are not legal chars (but are mid URL!)

Tested on 
* Android 11 
* Pixel 3a
* Unbranded 0.8.0 webview

## Error 1
The first error is that we give different messages:
* ` https://example.com` - leading space and NO trailing slash, error is: "must be a valid URL"
* ` https://example.com/` - leading space and YES trailing slash, error is: "URL is not a medic-webapp instance"
* `https://example.com ` - trailing space and NO trailing slash, error is: "unable to contact server"
* `https://example.com/ ` - trailing space and YES trailing slash, error is: "URL is not a medic-webapp instance"

steps to reproduce:
1. download unbranded android app
2. enter url with leading or trailing space
3. click "save"

expected: launch app connecting to URL
actual: errors per above

## Error 2
After entering a URL with a space at the beginning and no trailing slash, the launch screen now has a URL entry that when you click the app crashes

steps to reproduce:
1. download unbranded android app
2. enter url with leading space and no trailing slash: ` https://example.com` 
3. click "save"
4. see error c
5. use back button to to back to launch screen
6. click top entry for the URL you just entered on step two

expected: launch app connecting to URL (ideally), or at least show error URL is not a medic-webapp instance"
actual: app crashes b/c `Attempt to invoke virtual method 'void android.widget.TextView.setError(java.lang.CharSequence)' on a null object reference at org.medicmobile.webapp.mobile.SettingsDIalogActivity.a(SettingsDialogActivity.java:8)` (sorry - manually transcribing from screenshot - there may be typos here - see attached)

## Screenshots

![error1](https://user-images.githubusercontent.com/8253488/119406722-08958680-bc98-11eb-9fe7-780bf2c01a78.png)
![error2](https://user-images.githubusercontent.com/8253488/119406724-092e1d00-bc98-11eb-9f6e-baac25d6db23.png)
![error3](https://user-images.githubusercontent.com/8253488/119406726-092e1d00-bc98-11eb-9772-e2b8e2b6052f.png)
![error6](https://user-images.githubusercontent.com/8253488/119406728-09c6b380-bc98-11eb-8908-939ed838952c.png)
![error5](https://user-images.githubusercontent.com/8253488/119406822-2cf16300-bc98-11eb-919e-8a8c9d1eca8e.png)

**Comment by mrsarm** [comment]
Ready for AT, alpha release `v0.11.0-alpha-url-fix`, branch `178-fix-url-errors`, PR https://github.com/medic/cht-android/pull/233.

Ways to test the fix are well described above in the ticket description.

**Comment by ngaruko** [comment]
LGTM.
Tested the following scenarios:

1. URL with trailing slash,  NO leading  space and NO trailing space: `https://server.medic.org/`
2. URL with trailing slash,  leading  space and NO trailing space: `    https://server.medic.org/`
3. URL with trailing slash, NO leading  space and  trailing space: `https://server.medic.org/    `
4. URL with trailing slash,  leading  space and trailing space: `.   https://server.medic.org/.   `

5. URL with NO trailing slash,  NO leading  space and NO trailing space: `https://server.medic.org`
6.  URL with NO trailing slash,  leading  space and NO trailing space: `.   https://server.medic.org`
7. URL with NO trailing slash, NO leading  space and  trailing space: `https://server.medic.org.  `
8. URL with NO trailing slash,  leading  space and trailing space: `.   https://server.medic.org.   `

Feel free to merge @mrsarm .
