### ISSUE TITLE
Builds fail on forks of this public repo

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-android#184]
```
Run openssl aes-256-cbc -K $ANDROID_SECRETS_KEY -iv $ANDROID_SECRETS_IV -in secrets.tar.gz.enc -out ./secrets.tar.gz -d
iv undefined
Error: Process completed with exit code 1.
```

[Example](https://github.com/medic/cht-android/pull/183/checks?check_run_id=2773651615)

Open source projects are ideally open to external collaboration and able to have people contribute via forks. We might consider disabling the use of an official keystore for forked builds?

**Comment by mrsarm** [comment]
This become an major issue due that we need to merge https://github.com/medic/cht-android/pull/203 (new Alerte Niger flavor) from an external contributor. Working on a solution in the same PR.

**Comment by mrsarm** [comment]
Fixed on https://github.com/medic/cht-android/pull/203 that was successfully merged.
