### ISSUE TITLE
Upgrade scripts and guides to be able to publish new branded versions on Play Store

### ISSUE THREAD

**Issue by mrsarm** [medic/cht-android#200]
This is an spin-off of https://github.com/medic/cht-android/issues/164 , that I'm going to close because we made the necessary changes to be able to update _existing_ apps in the Play Store, while the purpose of this new ticket is to be able to _**create new**_ branded apps in the Play Store.

In summary, the new workflow proposed in this [document](https://docs.google.com/document/d/1ZAiY-67DHdX7AvFxZoXo_FLNwztG6zYdeN9PcwxFtmk/edit?usp=sharing) are:

- New apps from partners will have their own private keys to sign the app, not using the one that we currently use to sign existing apps.
- For each app, we will use the same key to sign the bundle (Upload Key) and to let Google sign the APKs (Signing App Key), allowing us to keep generating .apk files for sideloading, compatible with the .apk files generated by Google (signed with the same key).
- We will make changes in the CI pipeline to generate both .apk and .aab files, signed with the same key, so each time a new private key is generated to sign an app, we need to setup it in our repo. We need to document well each step to create a new flavored version of the app. We also recommend to only setup one key for partner, using the new key for each new flavored app created by that partner.
- After the creation of the app in our repo and in the Play Console, the owner of the Play account (partner or us) will register the key for signing, and upload the .aab file for publishing the release.
- The process of creating the key is complex and involves the usage of different commands, so we have to create scripts to facilitate and standardize the creation and configuration.

**Comment by mrsarm** [comment]
Sure @garethbowen , I just didn't want to delay the release, but I guess we can wait a bit unless there is a bug or new feature that need to be released soon.

My goal releasing v0.9.0 is to at least release the new debug future that is already released in CHT v3.12: https://github.com/medic/cht-android/pull/182

**Comment by garethbowen** [comment]
There's quite a lot of other issues scheduled in the 0.9.0 milestone currently. If we need to get a release out quickly I'd recommend creating a new 0.10.0 milestone and moving all the open issues (including this one) to that.

**Comment by mrsarm** [comment]
@garethbowen yes I'm sorting that out, but moving tasks to v1.0.0 instead. Do you think v1.0.0 is too far to move these tasks there?

**Comment by garethbowen** [comment]
v1.0.0 currently contains breaking changes, in particular, dropping support for Android 4.x. We want to ship a bunch of bug fixes and improvements as a stabilisation release before making that breaking change. Unless you think there is another breaking change, it'd be better to make a 0.10.0 than add them all to 1.0.0.

**Comment by mrsarm** [comment]
Gotcha! Going to create v0.10.0 and move some tasks there.
