### ISSUE TITLE
Build Error: new Gradle plugin required along with JDK 11

### ISSUE THREAD

**Issue by mrsarm** [medic/cht-android#201]
Merging a not so old PR got this [error](https://github.com/medic/cht-android/runs/3246619110) in CI:

```
> Task :lintUnbrandedWebviewDebug
/home/runner/work/cht-android/cht-android/build.gradle:11: Error: A newer version of com.android.tools.build:gradle than 4.2.2 is available: 7.0.0 [AndroidGradlePluginVersion]
    classpath 'com.android.tools.build:gradle:4.2.2'
...
> Task :lintUnbrandedWebviewDebug FAILED
...
```

So to pass the linter we need to upgrade the plugin, but reading the [plugin documentation](https://developer.android.com/studio/releases/gradle-plugin#7-0-0), in order to upgrade the plugin we also need to upgrade the Java version to JDK 11.

We did recently update from Java 6 to 8, so the upgrade to Java 11 should be easy, and makes sense because is the latest LTS version from Java and the only one supported at this moment.

**Comment by mrsarm** [comment]
Worth to note that after upgrading the plugin in my local development, a new range of linter checks were added by the plugin, and now there are more errors to fix:

![Screenshot from 2021-08-04 20-33-34](https://user-images.githubusercontent.com/1608415/128268743-36ec72ad-d36a-48c1-b8ef-1271e6188e39.png)

Tomorrow I'll work on each check one by one, some may require refactors and some others just disable the check depending of the error.

**Comment by mrsarm** [comment]
Ready for AT, release [v0.9.0-alpha.1](https://github.com/medic/cht-android/releases/tag/untagged-0f2e9979f31b2d5e56d3), PR https://github.com/medic/cht-android/pull/202.

Although the PR addresses build configurations, it makes changes that may affect the app, and it fixes and issue with the integrations we have (MDRT, Simprints), that only affect Android 11.

### Tests needed

- The apps continue to work both Webview and Xwalk. We should test the XWalk with an old phone to be sure it continues to work despite the update of the tooling, e.g. Android 4.4. No special workflow to test, just check that the app loads and the basic features continue to work like create a form (the oldest version I could test is Android 6).
- Check the MRDT integration continue to work with Android 11 (check steps bellow). The last stable version of the app available in the Play Store (v0.8) it doesn't, so this version also fix this. Checking the feature in and older Android device also is recommended to be sure the change didn't affect older versions.

### MRDT check

This is how I tested the MRDT integration:

1. Install the [reference MRDT](https://play.google.com/store/apps/details?id=edu.washington.cs.ubicomplab.rdt_reader) app in the same phone the CHT app is used.
2. Install the following [demo form](https://github.com/medic/cht-core/blob/master/demo-forms/mrdt-demo.xml) in a CHT instance from _App Management > App forms_.
3. Try to fill a RDT form from the CHT app. Go to _Reports > Submit report > MRDT Demo_.
4. See that in the form the wiget "MRDT image" is available. Clicking the button "Take photo" should launch the MRDT app.

**Comment by ngaruko** [comment]
Testing on Android 5.1 (oldest I have)
![image](https://user-images.githubusercontent.com/6979995/128815124-56d3f061-700c-4794-ab5c-8db1398f289e.png)
 and Android 10 (latest)
![image](https://user-images.githubusercontent.com/6979995/128815322-802fc2be-515f-460f-9b26-da260af055e3.png)
 Needs testing on android 11

**Comment by mrsarm** [comment]
Cool! thanks @newtewt and @ngaruko , I think all tests passed, can we move the ticket to _Ready to merge_ ?
