### ISSUE TITLE
Simprints integration is not working

### ISSUE THREAD

**Issue by mrsarm** [medic/cht-android#204]
Simprints integration is not working, if you have installed in the same device a Simprints compatible app, you get this in a form with the Simprints widget:

![Screenshot_20210809-115250_CHT Android](https://user-images.githubusercontent.com/1608415/128753046-e2189569-a816-4346-8d91-454c5b860710.png)

There are 2 different causes, being the first an issue in the CHT code and not in this app: https://github.com/medic/cht-core/issues/7241

The second issue would be only for Android 11 phones, that due changes in the Android system, we need to declare in the Manifest the querying of the Intent that triggers the Simprints app. This should be fixed in this PR: https://github.com/medic/cht-android/pull/202 , but until the first cause is not solved, we cannot test the PR changes, so I leave this ticket to keep track of the issue if we release the PR before fix the problem in the CHT.

**Comment by mrsarm** [comment]
Set low priority because talking about the issue in the Product meeting, looks like we don't have any Simprints integration actively used by the moment.

**Comment by garethbowen** [comment]
Closing - we're going to drop the integration until it's needed. #230
