### ISSUE TITLE
Remove the old menu and lock pin screen

### ISSUE THREAD

**Issue by latin-panda** [medic/cht-android#253]
**Describe the issue**
I found some old code: 

1. We have [a menu](https://github.com/medic/cht-android/blob/e107f89f9873a4fbed52d83e485660c42f1fe6d1/src/main/java/org/medicmobile/webapp/mobile/EmbeddedBrowserActivity.java#L166) that used to work with a menu button that old phones used to have, [this button was removed 8+ years ago](https://www.androidauthority.com/android-menu-button-is-dead-48604/). 

2. A [lock](https://github.com/medic/cht-android/blob/master/src/main/java/org/medicmobile/webapp/mobile/LockScreen.java) and [pin page](https://github.com/medic/cht-android/blob/master/src/main/res/layout/pin_entry.xml), see the design attached. I’ve never seen / heard this one actively working. I know there were some ideas about possibly adding something like this, but this code is very old, so if we ever want to add a pin then we can write a fresh modern code that is covered with testing.

<img width="300" src="https://user-images.githubusercontent.com/66472237/161080523-5910bff9-c0b2-42a7-bd85-e1b9d5dd9867.png">

**Describe the improvement you'd like**
Remove the menu and lock pin view.
Add a secret door to open the settings view to facilitate testing across instances.

**Comment by latin-panda** [comment]
Ready for AT in [this PR](https://github.com/medic/cht-android/pull/254)

AT recommendation:
- Testing that old devices are working fine even when clicking the old menu button (the one from the device, not the one from webapp) since we have removed the menu.
- Testing that app goes back, closes, open and navigates across tabs correctly. Since we removed that LockActivity because we don't use the lock pin view anymore, and the main activity that opens webapp was depending on this LockActivity. 
- Testing that the ["secret door"](https://github.com/medic/cht-android/pull/254/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R18) opens the Settings view, that going back from Settings view and then go again to Settings view works fine. If you tap on a clickable element, the clickable element have more priority than the "secret door" _and that's expected_, so tap in non-clickable elements, for example in the white background of area of targets or message module.

**Comment by ngaruko** [comment]
Most of the app seems to work. 
However, there is one little glitch: most up will exit when the user presses the back button "too many times", but our app does not seem to exit/_finish()_, even if there are no activities in the back stack.
Is this intentional @latin-panda ?

https://user-images.githubusercontent.com/6979995/163937067-c746311a-80ae-45bf-9aff-f9742d3bb9a6.mov

**Comment by latin-panda** [comment]
Yes, we're [preventing to close webapp](https://github.com/medic/cht-core/commit/6485177d7e71771165482e6dd725c7da791c6613#diff-b7146e718ae4f210bf082f8574ef794803f6a81d0d3cc47e424a0adc4ef062b1R165) when clicking on the back button, it was released in [v3.13](https://github.com/medic/cht-core/issues/6698).

**Comment by latin-panda** [comment]
Thanks @ngaruko!
