### ISSUE TITLE
Border not showing red for production URL in dev app

### ISSUE THREAD

**Issue by abbyad** [medic/cht-android#266]
**Describe the bug**
When using production URL in dev app the border of the app is meant to be red, but shows blue or grey.

**To Reproduce**
1. Install unbranded app
1. Use cht.app.medicmobile.org as the url
1. See border color not being red

**Expected behavior**
When using a *.app.medicmobile.org URL in the unbranded app I expect the border to appear, and be red.

**Screenshots**
![Screenshot_20220421-095806-400](https://user-images.githubusercontent.com/789512/164836132-6db7a241-cc8b-4ccd-b7e1-841591dd26f8.jpg)

**Environment**
- Android Version: 11
- App Version: v0.11.0-webview

**Additional context**
[This code](https://github.com/medic/cht-android/blob/5218167a3ea3c7b66767fa8296c405ec5c2e9608/src/main/java/org/medicmobile/webapp/mobile/EmbeddedBrowserActivity.java#L87-L93) adds the border but the color set with `setBackgroundColor` which uses the int of the resource itself, not the color it is defining -- which essentially means the border color is random since the resource ID can change with different builds. With #258 the color is set correctly [by using `setBackgroundResource`](https://github.com/medic/cht-android/blob/5218167a3ea3c7b66767fa8296c405ec5c2e9608/src/main/java/org/medicmobile/webapp/mobile/EmbeddedBrowserActivity.java#L99).

**Comment by latin-panda** [comment]
Ready for AT in this [PR](https://github.com/medic/cht-android/pull/267)

**Comment by lorerod** [comment]
**Phone:** Galaxy A01 Core
**Android Version:** 10
**Android System WebView Version:** 97.0.4692.98

### Reproducible on Master
**Platform:** Mobile App. APK generated with branch `master`
<details>
<summary> Environment: brac-ug.app.medicmobile.org </summary>

- The border is not red

![brag-upOnMaster](https://user-images.githubusercontent.com/21312057/166493038-f2b0f3a5-37cb-4ae8-8a84-e29c9cd58f9c.jpg)

![brag-ugOnMasterLogin](https://user-images.githubusercontent.com/21312057/166493034-b9be46e5-1684-417f-8ef6-53da595f2901.jpg)

</details>

<details>
<summary> Environment: cht.app.medicmobile.org </summary>

- The border is not red

![cht-appOnMaster](https://user-images.githubusercontent.com/21312057/166493412-a6c827f6-fe08-4d6a-891a-5019f821d27f.jpg)

![cht-appOnMasterLogin](https://user-images.githubusercontent.com/21312057/166493452-deb0fc9b-d003-43c3-a98d-0b597f15a8c6.jpg)

</details>

### Fixed on branch
**Platform:** Mobile App. APK generated with branch `266-fix-border-color`
<details>
<summary> Environment: brac-ug.app.medicmobile.org </summary>

- The border is red
![brac-ugOnBranch](https://user-images.githubusercontent.com/21312057/166493858-610f4dcb-a482-4d4b-b304-85431378c17e.jpg)

![brac-ugOnBranchLogin](https://user-images.githubusercontent.com/21312057/166493879-b8ccf5e7-d037-4f3e-b4bf-9bc08cb4f939.jpg)

</details>

<details>
<summary> Environment: cht.app.medicmobile.org </summary>

- The border is red
![cht-appOnBranch](https://user-images.githubusercontent.com/21312057/166493929-d915d645-fae4-4cd2-9e96-1bdf9bb443b9.jpg)

![cht-appOnBranchLogin](https://user-images.githubusercontent.com/21312057/166493949-5b8b164c-2d7b-4832-a44f-99d0fc1137e3.jpg)

</details>

**Comment by garethbowen** [comment]
Merged on behalf of @abbyad who is on location.
