### ISSUE TITLE
Fix Implicit Intent Vulnerability 

### ISSUE THREAD

**Issue by latin-panda** [medic/cht-android#282]
**Describe the bug**
We got the following error in Google Play Store:

![Screen Shot 2022-06-09 at 2 07 55 pm](https://user-images.githubusercontent.com/66472237/172786300-ba769278-318c-470a-8be6-c24d1c2e4e2a.png)

These links give more info about the error and fixes:
- [Remediation of Implicit Internal Intent Vulnerability](https://support.google.com/faqs/answer/10399926)
- [CWE-927: Use of Implicit Intent for Sensitive Communication](https://cwe.mitre.org/data/definitions/927.html)
- [Security tips: Use of intents](https://developer.android.com/training/articles/security-tips.html#use-intents)

>Applications that send broadcasts without specifying the broadcast target may have
these broadcasts intercepted by malicious apps on the same device.

(source: [Android_app_vulnerability_classes.pdf](https://github.com/medic/cht-android/files/8867752/Android_app_vulnerability_classes.pdf))

**Additional context**
Possibly introduced in [this PR](https://github.com/medic/cht-android/pull/165).

**Comment by latin-panda** [comment]
When testing this issue, make sure these features are working fine:
- https://github.com/medic/cht-android/issues/163
- https://github.com/medic/cht-android/issues/148

**Comment by latin-panda** [comment]
This is ready for AT [in this PR](https://github.com/medic/cht-android/pull/283), please consider to test these issues[ mentioned here](https://github.com/medic/cht-android/issues/282#issuecomment-1151875152).

**Comment by latin-panda** [comment]
We can't replicate, in our local, the same "Implicit Intent Vulnerability" error from Play Store. The lint and the static check tools aren't detecting it, it's a check from Play Store.  Once we ensure this fix didn't affect badly the existing functionality, then we're going to release and deploy to Play Store, wait until it finishes the checks and see if the error appears again.

**Comment by tatilepizs** [comment]
**Config:** Covid-19
**Environment:** Local with Docker helper script
**cht-core version:** master
Platform: Mobile App. APK generated with branch `282-Fix_Implicit_Intent_Vulnerability`

### Test - Ticket #163 

**Test scenario:**
Tested with four different phones. Removed internet connection to see the page indicating the error, after it was connected again to the internet, click on `Retry`, and the login page was displayed successfully.

<details>
<summary>Android 5.1</summary>

**Phone:** Alcatel OneTouch 50560
**Android System WebView Version:** 95.0.4638.74

<img width="250" alt="image" src="https://user-images.githubusercontent.com/94494491/173438594-981fe3c5-6741-440f-925e-f00b68a63ed0.png">
<img width="250" alt="image" src="https://user-images.githubusercontent.com/94494491/173438641-603c43cc-847b-435d-9260-da2692e86d92.png">
<img width="250" alt="image" src="https://user-images.githubusercontent.com/94494491/173438696-c78dce07-5d34-4d2e-80cb-55201387a379.png">

</details>

<details>
<summary>Android 9</summary>

**Phone:** Huawei P20 lite
**Android System WebView Version:** 74.0.3729.136

<img width="250" alt="image" src="https://user-images.githubusercontent.com/94494491/173439708-786d6690-ab67-4891-a93a-3a44c1bfd042.png">
<img width="250" alt="image" src="https://user-images.githubusercontent.com/94494491/173439774-fa3d2751-62ef-44c3-bdfe-3747a9ad8b7d.png">
<img width="250" alt="image" src="https://user-images.githubusercontent.com/94494491/173439821-0a888d37-ac70-403d-bc49-869e494b9666.png">

</details>

<details>
<summary>Android 10</summary>

**Phone:** Samsung Galaxy A01
**Android System WebView Version:** 101.0.4951.61 

<img width="250" alt="image" src="https://user-images.githubusercontent.com/94494491/173440637-a1682aff-5d4f-4538-a397-45cf719cf582.png">
<img width="250" alt="image" src="https://user-images.githubusercontent.com/94494491/173440671-779b2a2d-1ac1-4422-b01a-ad55daeda897.png">
<img width="250" alt="image" src="https://user-images.githubusercontent.com/94494491/173440715-bd500a8c-04ad-4573-866f-45a90b996e96.png">

</details>

<details>
<summary>Android 11</summary>

**Phone:** Ulefone Note 6
**Android System WebView Version:** 101.0.4951.41

<img width="250" alt="image" src="https://user-images.githubusercontent.com/94494491/173441430-515856f1-5a54-4d73-a07e-1771b302abc0.png">
<img width="250" alt="image" src="https://user-images.githubusercontent.com/94494491/173441481-2f403c14-9265-45b1-8470-9820acf4c96f.png">
<img width="250" alt="image" src="https://user-images.githubusercontent.com/94494491/173441495-cc514242-fc85-4ea1-9c28-5afb9b27a748.png">

</details>

### Test - Ticket #148 

**Test scenario:**
Tested with four different phones. Using the _RDT Covid-19 - Provision_ form, the `location` and `storage` disclosures were displayed successfully.

<details>
<summary>Android 5.1</summary>

**Phone:** Alcatel OneTouch 50560
**Android System WebView Version:** 95.0.4638.74

No disclosure was displayed for Android 5, everything was accepted during the installation.

<img width="250" alt="image" src="https://user-images.githubusercontent.com/94494491/173438954-92c432a0-fab8-46f8-a94e-e17feccba00f.png">

</details>

<details>
<summary>Android 9</summary>

**Phone:** Huawei P20 lite
**Android System WebView Version:** 74.0.3729.136

<img width="250" alt="image" src="https://user-images.githubusercontent.com/94494491/173439875-9f8ab8d3-11dc-4511-bd01-5b6d9f3b2193.png">
<img width="250" alt="image" src="https://user-images.githubusercontent.com/94494491/173439930-bd0e4245-f17f-44a6-a1ff-9bafdee89528.png">
<img width="250" alt="image" src="https://user-images.githubusercontent.com/94494491/173439961-c488d4d4-ea59-4c89-8e8b-0087888d73a9.png">
<img width="250" alt="image" src="https://user-images.githubusercontent.com/94494491/173439987-d9be0752-ae4e-4ae4-9f6e-dafc122ed414.png">
<img width="250" alt="image" src="https://user-images.githubusercontent.com/94494491/173440021-583111b7-91ae-4ad6-a5b6-9e50ae863b5d.png">

</details>

<details>
<summary>Android 10</summary>

**Phone:** Samsung Galaxy A01
**Android System WebView Version:** 101.0.4951.61 

<img width="250" alt="image" src="https://user-images.githubusercontent.com/94494491/173440776-e0e48dae-009d-4da7-a66c-ced4e2a6aa9a.png">
<img width="250" alt="image" src="https://user-images.githubusercontent.com/94494491/173440836-6bcac81b-2922-4e0b-9e26-f980e61ec006.png">
<img width="250" alt="image" src="https://user-images.githubusercontent.com/94494491/173440885-d31ff358-412e-401b-af9e-a1f8ca958355.png">
<img width="250" alt="image" src="https://user-images.githubusercontent.com/94494491/173440919-4823084a-ab44-4413-a0d9-2d51b22360d7.png">
<img width="250" alt="image" src="https://user-images.githubusercontent.com/94494491/173440958-e7cc89d1-b75b-46dd-86aa-606b12c2f4cb.png">


</details>

<details>
<summary>Android 11</summary>

**Phone:** Ulefone Note 6
**Android System WebView Version:** 101.0.4951.41

<img width="250" alt="image" src="https://user-images.githubusercontent.com/94494491/173441532-baacc87c-fe2a-4bf3-97fd-71670dda1ff4.png">
<img width="250" alt="image" src="https://user-images.githubusercontent.com/94494491/173441547-a872749c-d145-4732-b2fa-78bc1f557223.png">
<img width="250" alt="image" src="https://user-images.githubusercontent.com/94494491/173441563-65297834-07b3-44ab-8031-ea38386b9f4e.png">
<img width="250" alt="image" src="https://user-images.githubusercontent.com/94494491/173441574-6f60ec9e-2058-449e-84f5-afd099cde61a.png">
<img width="250" alt="image" src="https://user-images.githubusercontent.com/94494491/173441586-61e19863-d892-4f01-beb8-a16af495c602.png">


</details>
