### ISSUE TITLE
Can not install two flavors of CHT Android app of same version. 

### ISSUE THREAD

**Issue by yrimal** [medic/cht-android#287]
**Describe the bug**
Can not install two different apps of CHT Android or it's flavors. For example, if I am a supervisor for two of the medic's deployments and both have Android app of same version, I can't install one of the app if another is already deployed. This happens with CHT Android app as well. 

**To Reproduce**
1. Download and install CHT App for [CHIS](https://github.com/medic/cht-android/releases/download/v1.0.0/cht-android-v1.0.0-chis_ne-arm64-v8a-release.apk)
2. Download and try installing [Unbranded app](https://github.com/medic/cht-android/releases/download/v1.0.0/cht-android-v1.0.0-unbranded-arm64-v8a-release.apk) or any [Muso Mali](https://github.com/medic/cht-android/releases/download/v1.0.0/cht-android-v1.0.0-musomali-arm64-v8a-release.apk) or any other apk of same version. 
3. You will see an error saying app wasn't installed. 
4. If you'd tried Step 2 using `adb`, you'd get error like below: 
```
adb: failed to install /Users/yuvraj/Downloads/cht-android-v1.0.0-musomali-arm64-v8a-release.apk: Failure 
[INSTALL_FAILED_CONFLICTING_PROVIDER: Scanning Failed.: Can't install because provider name 
org.medicmobile.webapp.mobile.fileprovider (in package org.medicmobile.webapp.mobile.musomali) 
is already used by org.medicmobile.webapp.mobile.chis_ne]
```

**Expected behavior**
Second app should be installed without error. 

**Logs**
Adb Log: 
```
adb: failed to install /Users/yuvraj/Downloads/cht-android-v1.0.0-musomali-arm64-v8a-release.apk: Failure 
[INSTALL_FAILED_CONFLICTING_PROVIDER: Scanning Failed.: Can't install because provider name 
org.medicmobile.webapp.mobile.fileprovider (in package org.medicmobile.webapp.mobile.musomali) 
is already used by org.medicmobile.webapp.mobile.chis_ne]
```

**Environment**
- Android Version: (eg: 11) 
- App Version: (eg: 1.0)

**Additional context**
Different version of CHT Android app (for example: CHIS v1.0 and Muso mali v0.9) can be installed side by side.

**Comment by latin-panda** [comment]
Some notes:
- We set the file provider in the [manifest](https://github.com/medic/cht-android/blob/master/src/main/AndroidManifest.xml#L74)
- Maybe we can change the `android:authorities` to be unique per flavor, sample: `android:authorities="${applicationId}.fileprovider"` Not sure how to access the flavor name from here, needs research.

**Comment by garethbowen** [comment]
This is high priority to allow for side installs of testing apps, and also some projects rely on multiple flavors for multiple logins for users with many docs.

It looks like it's possible to inject the app id into the manifest: https://developer.android.com/studio/build/manage-manifests#inject_build_variables_into_the_manifest

Let's give this a try?

**Comment by tatilepizs** [comment]
User: CHW
Config: Default
Environment: Local with docker helper script 
cht-core version: master
Platform: Mobile App. APK generated with branch `287-install-many-flavors-at-the-same-time`

Four apps from different "flavors" installed in the same phone without issues

<details>
<summary>Android 5.1</summary>

**Phone:** Alcatel OneTouch 50560
**Android System WebView Version:** 95.0.4638.74

<img width="250" alt="image" src="https://user-images.githubusercontent.com/94494491/173937550-a1d04981-417f-4a8a-ae48-ee66db1e7f3d.png">

</details>

<details>
<summary>Android 10</summary>

**Phone:** Samsung Galaxy A01
**Android System WebView Version:** 101.0.4951.61 

<img width="250" alt="image" src="https://user-images.githubusercontent.com/94494491/173942046-d0d39e9d-ca3c-40f5-8124-896968944eb4.png">

</details>

File picker feature is working as expected.
<details>
<summary>Android 5.1</summary>

**Phone:** Alcatel OneTouch 50560
**Android System WebView Version:** 95.0.4638.74

[video](https://user-images.githubusercontent.com/94494491/173940982-d3002e69-fa52-48d9-9126-eb4ffed1a377.mp4)

</details>

<details>
<summary>Android 10</summary>

**Phone:** Samsung Galaxy A01
**Android System WebView Version:** 101.0.4951.61 

[video](https://user-images.githubusercontent.com/94494491/173942685-847ae228-0e81-4e1e-a1b4-c73623d1b9bf.mp4)


</details>

**Comment by yrimal** [comment]
<details><summary>Samsung Galaxy Tab A7 Lite</summary>

**OS**: Android 11
**Environment**: Muso Mali Production
**User**: adtest (CHW)
**Installed**: 4 flavors of fixed version. 
**Log**:
```
> ./adb install ~/Downloads/apk/unbranded/debug/cht-android-SNAPSHOT-unbranded-arm64-v8a-debug.apk
Performing Streamed Install
Success
> ./adb install ~/Downloads/apk/musomali/debug/cht-android-SNAPSHOT-musomali-arm64-v8a-debug.apk
Performing Streamed Install
Success
> ./adb install ~/Downloads/apk/moh_mali/debug/cht-android-SNAPSHOT-moh_mali-arm64-v8a-debug.apk
Performing Streamed Install
Success
> ./adb install ~/Downloads/apk/livinggoods/debug/cht-android-SNAPSHOT-livinggoods-arm64-v8a-debug.apk
Performing Streamed Install
Success

```

**Image:**
![image](https://user-images.githubusercontent.com/6102813/173981414-f7a0d79e-501d-49c5-a05c-e603380148b3.png)


</details>

**Comment by yrimal** [comment]
Verified by installing multiple flavors and logging in as users.
