### ISSUE TITLE
Play store compliance July 2022

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-android#291]
Investigate and solve play store compliance for the demo apps, and then communicate the process so app developers can comply as well.

- [ ] Privacy Policy. It appears that we now need to provide a URL as opposed to the process outlined in [this doc](https://docs.google.com/document/d/1zbQnZrxjSHK-imvBUXyqrlH6NCxDBLrovqSFUTAJdkA/edit). Develop a privacy policy, host it somewhere, then log in to the Play Store console > App Content > Privacy Policy and link to it.
- [ ] Fill in the Play Store > App Content > Data Safety form.
- [ ] Document everything you did and update app developers, docs site, forum, or anywhere else you can think of.

The update from Google states that...

> Your Data safety form must be submitted and approved by July 20, otherwise your app updates will be rejected. ... Non-compliant apps may face additional enforcement actions in the future, such as the removal of your app's store listing from Google Play.

Read the full message in the [Google Play Store Console Inbox](https://play.google.com/console/u/0/developers/7987044497930745454/app/4973604959552855131/inbox).

This will need to be done for all apps but hopefully it's a copy and paste job.

**Comment by garethbowen** [comment]
@abbyad That would probably work for Medic's apps but I don't feel comfortable dictating the privacy policy for partner apps.

@jkuester I was thinking about adding a new CHT feature to make the custom privacy policy available at a public URL on the server. This could be linked from the login page to follow best practice so people can read the privacy policy before logging in, and also give us a URL to send to Google. If one hasn't been provided it could default to the one Marc linked.

**Comment by abbyad** [comment]
> @abbyad That would probably work for Medic's apps but I don't feel comfortable dictating the privacy policy for partner apps.

Right, partners would need to decide what privacy policy to link to. @derickl, can you coordinate where needed to get the right policies in place for partner apps?

**Comment by mrjones-plip** [comment]
> I was thinking about adding a new CHT feature to make the custom privacy policy available at a public URL on the server. This could be linked from the login page to follow best practice so people can read the privacy policy before logging in, and also give us a URL to send to Google. If one hasn't been provided it could default to the one Marc linked.

As a privacy advocate and an Allies teammate - I LOVE this idea!!

**Comment by garethbowen** [comment]
@mrjones-plip Issue here: https://github.com/medic/cht-core/issues/7662

**Comment by garethbowen** [comment]
The compliance date has passed so I'm assuming projects have complied by now...
