### ISSUE TITLE
Update target API to latest

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-android#324]
From Google Play Store

> App must target Android 13 (API level 33) or higher
> To provide users with a safe and secure experience, Google Play requires all apps to meet target API level requirements.
> From 31 Aug 2023, if your target API level is not within one year of the latest Android release, you won't be able to update your app.

In other words, after August 31 we won't be able to publish updated (or presumably new) android apps until the target API is at least 33.

This has the potential to block new deployments going live so we need to fix this as soon as possible before then.

**Comment by ngaruko** [comment]
Testing apk from [PR](https://github.com/medic/cht-android/pull/325) :
<details>
 <summary> App installed successfully</summary>
 | Android 10  (SDK 29 ) | Android 12  (SDK 31) | Android 13  (SDK 33) |
| ------------- | ------------- | ------------- |
|  
![image](https://github.com/medic/cht-android/assets/6979995/07f2d72f-6ea0-4bd5-b9fb-a315b6fc9b49)
 |  
<img width="268" alt="image" src="https://github.com/medic/cht-android/assets/6979995/bda604b5-b483-47de-a831-2f165df65e31">
 | 
![image](https://github.com/medic/cht-android/assets/6979995/56bcc4ac-a6d8-4d42-9ef9-04d2ad15e54d)
 |
</details>

**Comment by latin-panda** [comment]
@ngaruko I found that to test sending reports by SMS, the permission needs to be enabled in the [manifest](https://github.com/medic/cht-android/blob/2061adccdb52b912a0ed79361284713e8494d71a/src/main/AndroidManifest.xml#L26), by default is commented. 

<details>
<summary>Screenshot of SMS that was sent after submitting report</summary>

<img src="https://github.com/medic/cht-android/assets/66472237/695e2ce0-0016-41f6-86e6-3a9f3cca4836" width="300">
</details>

**Comment by latin-panda** [comment]
@ngaruko I did these same [cases you tested](https://github.com/medic/cht-android/issues/324#issuecomment-1692724352) in Android 9 and 13, with these additional cases:
- Back button, no closing the app
- Training cards
- [Reports sending SMS](https://github.com/medic/cht-android/issues/324#issuecomment-1692941001) (on Android 13 only)

**Comment by ngaruko** [comment]
@latin-panda I have noticed the buck button not closing the app. Did the app launcher with the old MRDT app on Android 13 and 12. All good.

**Comment by garethbowen** [comment]
@latin-panda Can we close this now?
