### ISSUE TITLE
Unable to publish cht-android APKs - crash when installing fastlane

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-android#340]
**Describe the bug**
There is a crash in the CI process when publishing

**To Reproduce**
1. Tag a commit in master and push
2. CI fails with an error

**Expected behavior**
CI should publish

**Logs**
```
Run gem install fastlane --no-document --quiet
ERROR:  Error installing fastlane:
	The last version of domain_name (~> 0.5) to support your Ruby & RubyGems was 0.5.20190701. Try installing it with `gem install domain_name -v 0.5.20190701` and then running the current command again
	domain_name requires Ruby version >= 2.7.0. The current ruby version is 2.6.10.210.
```
https://github.com/medic/cht-android/actions/runs/7132831004/job/19424212511

**Environment**
- Instance: CARES
- Android Version: main

**Comment by latin-panda** [comment]
This is fixed. To test, I've created a [tag](https://github.com/medic/cht-android/releases/tag/v1.1.0-beta-2-fastlane-test) to trigger CI and run the Fastlane; [it's not crashing anymore](https://github.com/medic/cht-android/actions/runs/7137958007)
<img width="500" alt="Screenshot 2023-12-08 at 1 25 48 pm" src="https://github.com/medic/cht-android/assets/66472237/59d47e47-0783-4084-934c-147ebeb8a215">
<img width="500" alt="Screenshot 2023-12-08 at 1 26 04 pm" src="https://github.com/medic/cht-android/assets/66472237/7383a89d-3c9f-4e27-abb0-876402d9460f">
<img width="500" alt="Screenshot 2023-12-08 at 1 26 21 pm" src="https://github.com/medic/cht-android/assets/66472237/e390e68f-3905-4d57-8b8f-5162dba8e929">
