### ISSUE TITLE
Android app should navigate to root instead of the _rewrite path after webapp 3.5

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-android#94]
WebApp v3.5 uses the domain's root url instead of the /medic/_design/medic/_rewrite/ path. The app directly navigates to this rewrite path, which then redirects to root - this is an unnecessary performance hop and adds an extra layer of complexity to the cache. 

Continuation of medic/medic/issues/3986
First draft of a solution in https://github.com/medic/medic-android/pull/70

**Comment by mrsarm** [comment]
The PR https://github.com/medic/cht-android/pull/100 address this issue but need some changes, and because it's a breaking change (only affect old CHT instances though), we decided to move it to the v1.0.0 release.

**Comment by latin-panda** [comment]
This is ready for AT in [this PR](https://github.com/medic/cht-android/pull/252)
Additional recommendation for AT: 
- Settings page should validate the instance URL as usual.

**Comment by ngaruko** [comment]
Testing local cht-android build:
On `master`, app redirecting to `medic/_design/medic/ _rewrite` path before coming back to `rootUrl`
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/6979995/161446956-7dea84b6-549a-45a1-a2dd-0044a6958654.png">

`On branch`, app goes straight to `rootUrl`
<img width="1044" alt="image" src="https://user-images.githubusercontent.com/6979995/161447350-782d64b5-897d-458e-8023-f81bf3e60008.png">
Tested basic app functionality.
